[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2021"
authors = ["CPerezz <c.perezbaro@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
keccak256 = { path = "../keccak256" }
ff = { package="ff_ce" , version="0.11", features = ["derive"] }
poseidon-rs = { git = "https://github.com/arnaucube/poseidon-rs.git", rev = "233027d6075a637c29ad84a8a44f5653b81f0410" }
ethers-core = "0.6"
ethers-providers = "0.6"
halo2_proofs = { git = "https://github.com/scroll-tech/halo2.git", branch = "scroll-dev-0607" }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.14"
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
strum = "0.24"
hex = "0.4.3"
strum_macros = "0.24"

[dev-dependencies]
hex = "0.4.3"
mock = { path = "../mock" }
pretty_assertions = "1.0.0"
rand = "0.8"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
